### ISSUE TITLE
Generate api documentation from the raml files

### ISSUE THREAD

**Issue by robvanmieghem** [itsyouonline/home#1]

**Comment by mohabusama** [comment]
RAML1.0 is not yet fully supported. However, it is still WIP for different tools. We can wait until one is ready.

**Comment by robvanmieghem** [comment]
Without being fully supported, is there one that does not crash on our 1.0 spec and can already be used?

**Comment by mohabusama** [comment]
From what I tested, the failure is in version validation `#%RAML 1.0`. If I changed it to `0.8`, it fails on the spec.

**Comment by robvanmieghem** [comment]
Since most static html documentation generators do not support raml 1.0 yet, I propose to use Mulesoft's api console. Let's run it in a separate docker.

**Comment by robvanmieghem** [comment]
Is not really styled to blend in:
<img width="1280" alt="screen shot 2016-03-08 at 14 24 33" src="https://cloud.githubusercontent.com/assets/3511318/13602937/fbb41df4-e539-11e5-9481-652c1ede7615.png">

**Comment by robvanmieghem** [comment]
Fixed, embedded the api console in the identityserver so there is no need for a separate docker and absolute url's and styled accordingly
