### ISSUE TITLE
Manage personal information

### ISSUE THREAD

**Issue by robvanmieghem** [itsyouonline/home#11]
The only personal information kept now is the email address, one should be able to manage that.

**Comment by robvanmieghem** [comment]
Manage email addresses:
* https://github.com/itsyouonline/identityserver/commit/a606a10befe8f632ef670fb2d1ba855938df5b4d
* https://github.com/itsyouonline/identityserver/commit/f28975066af03fda262644429a45bd4df48212dd

**Comment by robvanmieghem** [comment]
Manage phone numbers:
https://github.com/itsyouonline/identityserver/commit/fbd5c2c55aab965d85f161f8c3bc3622293f3e29

**Comment by robvanmieghem** [comment]
Manage addresses:
* https://github.com/itsyouonline/identityserver/commit/2dbdc9c52f2b4cab47447e7ab5ee6b89100c74b9
* https://github.com/itsyouonline/identityserver/commit/faadfd273ec11957f380d62c96a5efd4730dc239

**Comment by robvanmieghem** [comment]
TODO: Manage bank accounts, facebook account, github account, bitcoin addresses and credit cards

**Comment by lvh1** [comment]
- [x] Bank accounts
- [ ] facebook account 
- [ ] github account
- [ ] credit cards
